from langchain_openai import ChatOpenAI
from oci_genai_auth import OciUserPrincipalAuth
import httpx
import asyncio
from openai import OpenAI, AsyncOpenAI
from typing import List, Mapping, Optional
from openai.types.chat import ChatCompletionMessageParam
from langchain_core.messages import HumanMessage

"""
OCIOpenAIHelper: Utility class for initializing OpenAI-compatible clients with OCI Generative AI authentication.

This module provides static methods to create OpenAI-compatible clients for interacting with OCI Generative AI:

- LangChain ChatOpenAI clients for LangChain integrations
- Direct OpenAI (OpenAI, AsyncOpenAI) clients configured for OCI endpoints
- Legacy OCI wrapper methods that raise migration errors instead of sending compartment or conversation store IDs

OpenAI-compatible clients are configured with OCI user principal authentication and Generative AI Project headers.
GA clients should not send compartment ID or conversation store ID headers.

Documentation to reference:
- Oracle LangChain OCI Examples: https://github.com/oracle/langchain-oracle/tree/main/libs/oci/examples
- OCI OpenAI SDK Examples: https://github.com/oracle-samples/oci-openai/tree/main/examples
- LangChain OpenAI Responses API: https://docs.langchain.com/oss/python/integrations/chat/openai#responses-api
- OCI Generative AI Platform GA Migration Guide: https://confluence.oraclecorp.com/confluence/display/OCAS/Generative+AI+Platform+Agentic+Capabilities+User+Guide#GenerativeAIPlatformAgenticCapabilitiesUserGuide-GAMigrationGuidanceforLAorBetacustomer

Env setup:
- sandbox.yaml: OCI configuration file containing profile name and Generative AI Project OCID
- Ensure OCI CLI is configured with user principal authentication
"""

# generated by codex AI - model GPT-5
GENAI_OPENAI_BASE_URL = "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/openai/v1"
GA_MIGRATION_GUIDE_URL = (
    "https://confluence.oraclecorp.com/confluence/display/OCAS/"
    "Generative+AI+Platform+Agentic+Capabilities+User+Guide"
    "#GenerativeAIPlatformAgenticCapabilitiesUserGuide-"
    "GAMigrationGuidanceforLAorBetacustomer"
)
LEGACY_OCI_HEADERS = {
    "opc-compartment-id",
    "compartmentid",
    "opc-conversation-store-id",
}


class MigrationRequiredError(RuntimeError):
    """Raised when legacy helper methods must migrate to project-based clients."""


class OCIOpenAIHelper:

    @staticmethod
    def _get_project_id(config, project_id: Optional[str] = None) -> str:
        if project_id:
            return project_id

        try:
            project_id = config["oci"]["project"]
        except (KeyError, TypeError) as exc:
            raise ValueError(
                "Missing required sandbox.yaml value: oci.project. "
                f"Create an OCI Generative AI Project and add its OCID. See {GA_MIGRATION_GUIDE_URL}"
            ) from exc

        if not project_id:
            raise ValueError(
                "sandbox.yaml value oci.project is empty. "
                f"Create an OCI Generative AI Project and add its OCID. See {GA_MIGRATION_GUIDE_URL}"
            )

        return project_id

    @staticmethod
    def _get_project_headers(
        project_id: str,
        default_headers: Optional[Mapping[str, str]] = None,
    ) -> dict[str, str]:
        headers = {
            key: value
            for key, value in dict(default_headers or {}).items()
            if key.lower() not in LEGACY_OCI_HEADERS
        }
        headers["OpenAI-Project"] = project_id
        return headers

    @staticmethod
    def _raise_ga_migration_error(method_name: str, replacement: str):
        raise MigrationRequiredError(
            f"{method_name} is disabled for the OCI Generative AI GA project migration. "
            "It relies on legacy OCI wrapper behavior that requires compartment_id and/or "
            "conversation_store_id. Use "
            f"{replacement}, which sends the Generative AI Project instead. "
            f"Migration guide: {GA_MIGRATION_GUIDE_URL}"
        )

    @staticmethod
    def _drop_request_level_model_kwargs(kwargs: dict) -> None:
        kwargs.pop("model", None)
        kwargs.pop("model_name", None)

    @staticmethod 
    def get_langchain_ocigenai_client(model_name, config, store=False, **kwargs):
        OCIOpenAIHelper._raise_ga_migration_error(
            "get_langchain_ocigenai_client",
            "get_langchain_openai_client",
        )
     
    
    @staticmethod
    def get_langchain_ociopenai_client(model_name, config, store=False, **kwargs):
        """
        Disabled legacy method for the LangChain ChatOCIOpenAI wrapper.

        ChatOCIOpenAI currently requires compartment_id, which is not compatible with
        the OCI Generative AI GA project migration for OpenAI-compatible APIs.

        Args:
            model_name (str): Model identifier, e.g., "openai.gpt-4.1" or "meta.llama-3.1-70b-instruct"
            config (EnvYAML): Configuration object loaded from YAML.
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Ignored. Kept for backwards-compatible method signature.

        Raises:
            MigrationRequiredError: Use get_langchain_openai_client instead.
        """

        OCIOpenAIHelper._raise_ga_migration_error(
            "get_langchain_ociopenai_client",
            "get_langchain_openai_client",
        )
    
   

    @staticmethod
    def get_langchain_openai_client(model_name, config, store=False, **kwargs):
        """
        Create a LangChain ChatOpenAI client configured for OCI Generative AI endpoints.

        Initializes a ChatOpenAI client pointing to OCI's OpenAI-compatible API endpoints with authentication.

        Args:
            model_name (str): Model identifier, e.g., "openai.gpt-4.1"
            config (EnvYAML): Configuration object with OCI settings
            **kwargs: Additional arguments for ChatOpenAI (supports use_responses_api=True for responses API)

        Returns:
            ChatOpenAI: LangChain client configured for OCI

        Notes:
            Uses httpx client with OCI authentication. Model is specified per call or via model_name.
        """

        project_id = OCIOpenAIHelper._get_project_id(config, kwargs.pop("project", None))
        default_headers = OCIOpenAIHelper._get_project_headers(
            project_id,
            kwargs.pop("default_headers", None),
        )
        use_responses_api = kwargs.pop("use_responses_api", True)

        client = ChatOpenAI(
            base_url=GENAI_OPENAI_BASE_URL,
            http_client=httpx.Client(auth=OciUserPrincipalAuth(profile_name=config['oci']['profile'])),  # or OciResourcePrincipalAuth | OciInstancePrincipalAuth | OciUserPrincipalAuth,
            http_async_client=httpx.AsyncClient(auth=OciUserPrincipalAuth(profile_name=config['oci']['profile'])),
            default_headers=default_headers,
            api_key=kwargs.pop("api_key", "not-used"),
            model=model_name,
            store=store,
            use_responses_api=use_responses_api,
            **kwargs
        )
        return client
    
   
   
    @staticmethod
    def get_sync_ociopenai_client(config, store=False, **kwargs):
        """
        Disabled legacy method for the synchronous OCI OpenAI wrapper.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Ignored. Kept for backwards-compatible method signature.

        Raises:
            MigrationRequiredError: Use get_sync_openai_client instead.
        """


        OCIOpenAIHelper._raise_ga_migration_error(
            "get_sync_ociopenai_client",
            "get_sync_openai_client",
        )

    @staticmethod
    def get_async_ociopenai_client(config, store=False, **kwargs):
        """
        Disabled legacy method for the asynchronous OCI OpenAI wrapper.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Ignored. Kept for backwards-compatible method signature.

        Raises:
            MigrationRequiredError: Use get_async_openai_client instead.
        """


        OCIOpenAIHelper._raise_ga_migration_error(
            "get_async_ociopenai_client",
            "get_async_openai_client",
        )
           
    @staticmethod
    def get_sync_openai_client(config, store=False, **kwargs):
        """
        Create a synchronous OpenAI client configured for OCI endpoints.

        Returns a direct OpenAI client pointing to OCI's OpenAI-compatible API.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Additional arguments for OpenAI

        Returns:
            OpenAI: Synchronous client for chat completions and responses

        Notes:
            Uses httpx client with OCI authentication. Model specified per API call.
        """
        project_id = OCIOpenAIHelper._get_project_id(config, kwargs.pop("project", None))
        default_headers = OCIOpenAIHelper._get_project_headers(
            project_id,
            kwargs.pop("default_headers", None),
        )
        OCIOpenAIHelper._drop_request_level_model_kwargs(kwargs)

        client = OpenAI(
            base_url=GENAI_OPENAI_BASE_URL,
            api_key=kwargs.pop("api_key", "not-used"),  # type: ignore
            project=project_id,
            # store is specified per request
            http_client=httpx.Client(auth=OciUserPrincipalAuth(profile_name=config['oci']['profile'])),  # or OciResourcePrincipalAuth | OciInstancePrincipalAuth | OciUserPrincipalAuth,
            default_headers=default_headers,
            **kwargs
            )

        return client 

    @staticmethod
    def get_async_openai_client(config, store=False, **kwargs):
        """
        Create an asynchronous OpenAI client configured for OCI endpoints.

        Returns a direct AsyncOpenAI client pointing to OCI's OpenAI-compatible API.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Additional arguments for AsyncOpenAI

        Returns:
            AsyncOpenAI: Asynchronous client for chat completions and responses

        Notes:
            Uses httpx AsyncClient with OCI authentication. Model specified per API call.
        """
        project_id = OCIOpenAIHelper._get_project_id(config, kwargs.pop("project", None))
        default_headers = OCIOpenAIHelper._get_project_headers(
            project_id,
            kwargs.pop("default_headers", None),
        )
        OCIOpenAIHelper._drop_request_level_model_kwargs(kwargs)

        client = AsyncOpenAI(
            base_url=GENAI_OPENAI_BASE_URL,
            api_key=kwargs.pop("api_key", "not-used"),  # type: ignore
            # store is specified per request
            project=project_id,
            http_client=httpx.AsyncClient(auth=OciUserPrincipalAuth(profile_name=config['oci']['profile'])),  # or OciResourcePrincipalAuth | OciInstancePrincipalAuth | OciUserPrincipalAuth,
            default_headers=default_headers,
            **kwargs
            )

        return client  
   
    @staticmethod
    def get_sync_openai_key_client(config, store=False, **kwargs):
        """
        Create a synchronous OpenAI client configured for OCI endpoints.

        Returns a direct OpenAI client pointing to OCI's OpenAI-compatible API.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Additional arguments for OpenAI

        Returns:
            OpenAI: Synchronous client for chat completions and responses

        Notes:
            Uses httpx client with OCI authentication. Model specified per API call.
        """
        project_id = OCIOpenAIHelper._get_project_id(config, kwargs.pop("project", None))
        default_headers = OCIOpenAIHelper._get_project_headers(
            project_id,
            kwargs.pop("default_headers", None),
        )
        OCIOpenAIHelper._drop_request_level_model_kwargs(kwargs)

        client = OpenAI(
            base_url=GENAI_OPENAI_BASE_URL,
            api_key=kwargs.pop("api_key", config['oci']['api_key']),
            project=project_id,
            default_headers=default_headers,
            **kwargs
            )

        return client 

    @staticmethod
    def get_async_openai_key_client(config, store=False, **kwargs):
        """
        Create a asynchronous OpenAI client configured for OCI endpoints.

        Returns a direct OpenAI client pointing to OCI's OpenAI-compatible API.

        Args:
            config (EnvYAML): OCI configuration
            store (bool, optional): Whether to store conversations. Defaults to False.
            **kwargs: Additional arguments for OpenAI

        Returns:
            OpenAI: Synchronous client for chat completions and responses

        Notes:
            Uses httpx client with OCI authentication. Model specified per API call.
        """
        project_id = OCIOpenAIHelper._get_project_id(config, kwargs.pop("project", None))
        default_headers = OCIOpenAIHelper._get_project_headers(
            project_id,
            kwargs.pop("default_headers", None),
        )
        OCIOpenAIHelper._drop_request_level_model_kwargs(kwargs)

        client = AsyncOpenAI(
            base_url=GENAI_OPENAI_BASE_URL,
            api_key=kwargs.pop("api_key", config['oci']['api_key']),
            project=project_id,
            default_headers=default_headers,
            **kwargs
            )

        return client 
     

##### test ######


def test_langchain_ocigenai_audio(model_name="openai.gpt-audio", question="who are you ? answer in one sentence"):
    print("############################################################")
    print(f"# Testing LangChain OCIGenAi Audio Chat: {model_name}")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    sync_llm = OCIOpenAIHelper.get_langchain_ociopenai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE))
    sync_msg = sync_llm.invoke(test_messages)
    print("sync responses output:", sync_msg.model_dump_json(indent=2))
    

def test_langchain_ocigenai_sync_chat(model_name="google.gemini-2.5-flash-lite", question="who are you ? answer in one sentence"):
    print("############################################################")
    print(f"# Testing LangChain OCIGenAI Sync Chat: {model_name}")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    sync_llm = OCIOpenAIHelper.get_langchain_ocigenai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE),provider="generic")
    sync_msg = sync_llm.invoke(test_messages)
    print("sync responses output:", sync_msg.model_dump_json(indent=2))
    

def test_langchain_ociopenai_sync_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OCI OpenAI Sync Chat")
    print("############################################################")
    print("not possible using oci client. as responses is hard coded to be true")
   
def test_langchain_ociopenai_sync_responses(model_name="openai.gpt-4.1",question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OCI OpenAI Sync Responses")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    sync_llm = OCIOpenAIHelper.get_langchain_ociopenai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE))
    sync_msg = sync_llm.invoke(test_messages)
    print("sync responses output:", sync_msg.model_dump_json(indent=2))

def test_langchain_openai_sync_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OpenAI Sync Chat")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    sync_llm = OCIOpenAIHelper.get_langchain_openai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE))
    sync_msg = sync_llm.invoke(test_messages)
    print("sync chat completion output:", sync_msg.model_dump_json(indent=2))
    
    
   
def test_langchain_openai_sync_responses(model_name="openai.gpt-4.1",question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain Openai Sync Responses")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    sync_llm = OCIOpenAIHelper.get_langchain_openai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE), use_responses_api=True)
    sync_msg = sync_llm.invoke(test_messages)
    print("sync responses output:", sync_msg.model_dump_json(indent=2))
    
def test_ociopenai_sync_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OCI OpenAI Sync Chat")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_sync_ociopenai_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    completion = llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 

def test_ociopenai_sync_responses(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OCI OpenAI Sync Responses")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_sync_ociopenai_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    response = llm.responses.create(
       model=model_name,
       input=question,
       store=False
    )
    
    print(response.model_dump_json(indent=2)) 

def test_openai_sync_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Sync Chat")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_sync_openai_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    completion = llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 

def test_openai_key_sync_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Sync Chat using key")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_sync_openai_key_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    completion = llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 
    
def test_openai_sync_responses(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Sync Responses")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_sync_openai_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    response = llm.responses.create(
       model=model_name,
       input=question,
       store=False
    )
    
    print(response.model_dump_json(indent=2)) 

def test_openai_key_sync_responses(model_name="openai.gpt-5.2", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Sync Responses using key")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_sync_openai_key_client(config=load_config(SANDBOX_CONFIG_FILE)) 
    response = llm.responses.create(
       model=model_name,
       input=question,
       store=False
    )
    
    print(response.model_dump_json(indent=2)) 
        

async def test_langchain_ociopenai_async_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OCI OpenAI Async Chat")
    print("############################################################")
    print("not possible using oci client. as responses is hard coded to be true")
   
async def test_langchain_ociopenai_async_responses(model_name="openai.gpt-4.1",question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OCI OpenAI Async Responses")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
    async_llm = OCIOpenAIHelper.get_langchain_ociopenai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE))
    async_msg = await async_llm.ainvoke(test_messages)
    print("async responses output:", async_msg.model_dump_json(indent=2))

async def test_langchain_openai_async_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain OpenAI Async Chat")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    async_llm = OCIOpenAIHelper.get_langchain_openai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE))
    async_msg = await async_llm.ainvoke(test_messages)
    print("async chat completion output:", async_msg.model_dump_json(indent=2))
    
    
   
async def test_langchain_openai_async_responses(model_name="openai.gpt-4.1",question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing LangChain Openai Async Responses")
    print("############################################################")
    test_messages = [HumanMessage(content=question)]
    async_llm = OCIOpenAIHelper.get_langchain_openai_client(model_name=model_name,config=load_config(SANDBOX_CONFIG_FILE), use_responses_api=True)
    async_msg = await async_llm.ainvoke(test_messages)
    print("async responses output:", async_msg.model_dump_json(indent=2))
    
async def test_ociopenai_async_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OCI OpenAI Async Chat")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_async_ociopenai_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    completion = await llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 

async def test_ociopenai_async_responses(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OCI OpenAI Async Responses")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_async_ociopenai_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    response = await llm.responses.create(
       model=model_name,
       input=question,
       store=False
    )
    
    print(response.model_dump_json(indent=2)) 

async def test_openai_async_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Async Chat")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_async_openai_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    completion = await llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 

async def test_openai_async_responses(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Async Responses")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_async_openai_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    response = await llm.responses.create(
       model=model_name,
       input=question,
#       store=False
    )
    
    print(response.model_dump_json(indent=2)) 
    

async def test_openai_key_async_chat(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Async Chat")
    print("############################################################")
    test_messages: List[ChatCompletionMessageParam] = [
        {
            "role": "user",
            "content": question
        }
    ]
        
    llm = OCIOpenAIHelper.get_async_openai_key_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    completion = await llm.chat.completions.create(
       model=model_name,
       messages=test_messages 
    )
    
    print(completion.model_dump_json(indent=2)) 

async def test_openai_key_async_responses(model_name="openai.gpt-4.1", question="who are you ? answer in one sentence"):
    print("############################################################")
    print("# Testing OpenAI Async Responses")
    print("############################################################")
        
    llm = OCIOpenAIHelper.get_async_openai_key_client(config=load_config(SANDBOX_CONFIG_FILE),store=False) 
    response = await llm.responses.create(
       model=model_name,
       input=question,
#       store=False
    )
    
    print(response.model_dump_json(indent=2)) 
        
if __name__ == "__main__":
    from dotenv import load_dotenv
    from envyaml import EnvYAML
    load_dotenv()
    SANDBOX_CONFIG_FILE = "sandbox.yaml"

    def load_config(config_path):
        """Load configuration from a YAML file."""
        try:
            with open(config_path, 'r') as f:
                return EnvYAML(config_path)
        except FileNotFoundError:
            print(f"Error: Configuration file '{config_path}' not found.")
            return None
        
    messages = [
        (
            "system",
            "You are a helpful assistant that translates English to French. Translate the user sentence.",
        ),
        ("human", "I love programming."),
    ]

#    test_langchain_ocigenai_sync_chat(model_name="google.gemini-2.5-flash-lite", question="where is paris? ")
#    test_langchain_ocigenai_audio(model_name="openai.gpt-audio", question="where is paris? ") 
    
    ## ok  
    # test_langchain_ociopenai_sync_chat(model_name="openai.gpt-4.1",question="where is paris?")
    #test_langchain_ociopenai_sync_responses(model_name="openai.gpt-4.1", question="where is paris? ")

    test_langchain_openai_sync_chat(model_name="openai.gpt-4.1",question="where is paris?")
    test_langchain_openai_sync_responses(model_name="openai.gpt-4.1", question="where is paris? ")

    
    # test_ociopenai_sync_chat(model_name="openai.gpt-4.1", question="where is paris? ")
    # test_ociopenai_sync_responses(model_name="openai.gpt-4.1", question="where is paris? ")

    # test_openai_sync_chat(model_name="openai.gpt-4.1", question="where is paris? ")
    # test_openai_sync_responses(model_name="openai.gpt-4.1", question="where is paris? ")
    # test_openai_key_sync_chat(model_name="openai.gpt-4.1", question="where is paris? ")
    # test_openai_key_sync_responses(model_name="openai.gpt-5.2", question="where is paris? ")

    # asyncio.run(test_langchain_ociopenai_async_chat())

    #fail asyncio.run(test_langchain_ociopenai_async_responses())

    # asyncio.run(test_langchain_openai_async_chat())
    # asyncio.run(test_langchain_openai_async_responses())
    # asyncio.run(test_ociopenai_async_chat())
    # asyncio.run(test_ociopenai_async_responses())
    # asyncio.run(test_openai_async_chat())
    # asyncio.run(test_openai_async_responses())
    # asyncio.run(test_openai_key_async_chat())
    # asyncio.run(test_openai_key_async_responses())
